apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/home/santosh/workshops/kubernetes"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-prometheus-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce


---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  serviceName: prometheus
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: docker.io/prom/prometheus:v2.36.2
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: config-volume-prometheus
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
        - name: data
          mountPath: /prometheus
      volumes:
        - name:  config-volume-prometheus
          configMap:
            name: prometheus-config
        - name: data
          persistentVolumeClaim:
            claimName: volume-prometheus-pvc